# Generated by Django 5.2.4 on 2025-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('mechanic', 'Mechanic'), ('plumber', 'Plumber'), ('electrician', 'Electrician'), ('cleaner', 'Cleaner'), ('baker', 'Baker'), ('gardener', 'Gardener'), ('painter', 'Painter'), ('carpenter', 'Carpenter'), ('tailor', 'Tailor'), ('mamafua', 'Mamafua'), ('mason', 'Mason'), ('chef', 'Chef'), ('hairdresser', 'Hairdresser'), ('photographer', 'Photographer'), ('tutor', 'Tutor'), ('home_repairs', 'Home Repairs & Maintenance')], max_length=50),
        ),
    ]
